added search option to aiko, fixed interrupt bug

diff --git a/aiko b/aiko
--- a/aiko
+++ b/aiko
@@ -12,39 +12,65 @@
 foreground="\e[0;39m"
 brown="\e[1;33m"
 
+password() {
+	sudo echo ""
+	if [[ "$?" -ge 1 ]]; then
+		exit
+	fi
+}
+
+search() {
+	path="$(ports -l | grep "$term")"
+	count="$(echo "$path" | wc -w)"
+
+	if [[ "$count" -ge 2 ]]; then
+		echo -e "There are $count packages that include $brown$term$foreground:\n"
+		if [[ "$type" == search ]]; then
+			echo -e "$(echo "$path" | sed "s/^ */        /g" | GREP_COLOR="1;33" grep --color=always "$term")\n"
+		elif [[ "$type" == install ]]; then
+			echo -e "$(echo "$path" | nl | sed "s/^ */  /g" | GREP_COLOR="1;33" grep --color=always "$term")\n"
+			read -p "Which package do you want to install? [1-$count] " answer
+			case "$answer" in
+				[1-$count])
+					path="$(echo "$path" | cut -d $'\n' -f $answer)"
+					echo ""
+					;;
+				*)
+					echo "TODO"
+					continue
+					;;
+			esac
+		fi
+	elif [[ "$count" -eq 0 ]]; then
+		echo -e "No package that includes $brown$term$foreground could be found."
+		echo ""
+		continue
+	fi
+}
+
 if [[ "$#" -ge 1 ]]; then
 	case "$1" in
 		-h|--help)
-			# TODO: Add change active escapism option
+			echo "-s pkg     search for pkg"
 			echo "+ pkg      install pkg"
 			echo "- pkg      uninstall pkg"
 			echo "           update"
 			;;
-		+)
+		-s)
+			type=search
+
 			shift
 			for term in $@; do
-				path="$(ports -l | grep "$term")"
-				count="$(echo "$path" | wc -w)"
+				search
+			done
+			shift
+			;;
+		+)
+			type=install
 
-				if [[ "$count" -ge 2 ]]; then
-					echo -e "There are $count packages that include $brown$term$foreground:\n"
-					echo -e "$(echo "$path" | nl | sed "s/^ */  /g" | GREP_COLOR="1;33" grep --color=always "$term")\n"
-					read -p "Which package do you want to install? [1-$count] " answer
- 					case "$answer" in
-						[1-$count])
-							path="$(echo "$path" | cut -d $'\n' -f $answer)"
-							echo ""
-							;;
-						*)
-							echo "TODO"
-							continue
-							;;
-					esac
-				elif [[ "$count" -eq 0 ]]; then
-					echo -e "No package that includes $brown$term$foreground could be found."
-					echo ""
-					continue
-				fi
+			shift
+			for term in $@; do
+				search
 
 				pkg="$(echo "$path" | cut -d "/" -f 2)"
 
@@ -80,7 +106,7 @@ if [[ "$#" -ge 1 ]]; then
 							done
 
 							current=0
-							sudo echo ""
+							password
 							;;
 						*)
 							echo "TODO"
@@ -97,7 +123,7 @@ if [[ "$#" -ge 1 ]]; then
 							;;
 						*)
 							current=-1
-							sudo echo ""
+							password
 							;;
 					esac
 				fi
@@ -120,7 +146,7 @@ if [[ "$#" -ge 1 ]]; then
 					fi
 				done
 
-				echo -e "Installing package $((count + 1))/$((count + 1)), $brown$path$foreground."
+				echo -e "Installing package, $brown$path$foreground."
 
 				cd "/usr/ports/$path"
 
@@ -133,7 +159,7 @@ if [[ "$#" -ge 1 ]]; then
 				if [[ "$?" -eq 0 ]]; then
 					notify "Installed package [$path]" & disown
 				else
-					echo -e "Failed to install package $((count + 1))/$((count + 1)), $brown$path$foreground."
+					echo -e "Failed to install package, $brown$path$foreground."
 					notify "Failed to install package [$path]" & disown
 					exit
 				fi
@@ -147,7 +173,7 @@ if [[ "$#" -ge 1 ]]; then
 	esac
 else
 	echo "Updating ports tree."
-	sudo echo ""
+	password
 	sudo ports -u
 	echo ""
 	prt-get diff
