Revert "neet: Small updates and fixes."
This reverts commit bf59319c4c143091501e3dd5db049635da8488c0.

diff --git a/punf b/punf
--- a/punf
+++ b/punf
@@ -1,211 +1,153 @@
 #!/bin/fish
 #
-# neet - A script to easily play and manage your anime/kdrama/etc.
+# punf - Upload files/scrots/urls to sr.ht (rip pomf & uguu)
 # onodera, https://github.com/onodera-punpun
 
 ## CONFIGURATION
 
-# Set media and config dir locations
-set configdir $HOME/.neet
-set mediadir $HOME/media/videos
+# Your sr.ht key
+set key (cat $HOME/.srht)
 
-# Set colors
-set fg normal
-set c1 yellow
+# Log urls
+set log false
 
-# Pause mpd on play (requires mpc)
-set pausempd true
+# Set log location
+set logfile $HOME/.punf
 
-# mpv launch options
-set options --fullscreen
+# Copy links to clipboard (requires xclip)
+set clipboard true
+
+# Send notification when upload is done (requires my notify script)
+set notify true
+
+# Open url in browser
+set browser false
 
 
 ## FUNCTIONS
 
-# This function gets basic media info, like the active show name, episode count and total episodes
-function info
-	# Get the active show (+)
-	set active (grep -B 1 + $configdir/list)
+# This function sets $file to your clipboard contents
+function clipboard
+	set -g uploadme /tmp/clipboard.txt
 
-	# Get the show name, current episode and total episode count
-	set -g name (echo $active[-2])
-	
-	if test -z $current
-		set -g current (echo $active[2] | cut -d / -f 1 | cut -c 3-)
-	end
-	set -g total (echo $active[2] | cut -d / -f 2)
+	xclip -o > $uploadme
+
+	set -g word clipboard
 end
 
-# This function tries to fuzzy find the right directory
-function directory
-	# Check if the show already has an alias
-	if test -n (grep "^$name=" $configdir/alias) -a $realias = false
-		set -g path (grep "^$name=" $configdir/alias | cut -d = -f 2)
-		return
-	end
+# This function sets $file to a selection scrot
+function selection
+	set -g uploadme /tmp/scrot.png
 
-	# Lists all directories in mediadir
-	set directories (ls -d $mediadir/* | rev | cut -d / -f -2 | rev)
-	
-	# This is the actual fuzzy logic part, it compares the directory names with the active show name
-	# TODO: Make this only grep whole words
-	set matches (
-		for directory in $directories
-			for word in (echo $name | tr \  \n)
-				echo $directory | grep -i $word
-			end
-		end | cut -d / -f 2 | uniq -c | sort | sed s/\ \ \ \*//g
-	)
-
-	# This greps the output wiith the most matches
-	# TODO Fix highest with slices
-	set highest (echo $matches | head -c 1)
-	set -g path (echo $matches[-1] | cut -d \  -f 2-)
-
-	# Count results
-	set count (echo $path | wc -l)
-	
-	# Create alias
-	# TODO: Fix Show initialized. in -d
-	if test $count -eq 1
-		echo "Show initialized. (alias set)"
-		echo $name=$path > "$configdir/alias"
-	else if test $count -ge 2
-		echo -e "There are $count directories that match "(set_color $c1)"$name"(set_color $fg)":\n"
-		echo -e "(echo $path | uniq | nl | sed s/\i/\ /g)\n"
-		read -p "Which directory would you like to use? [1-$count] " answer
-		if test (seq $count | grep "^$answer\$")
-			echo -e "\nShow initialized. (alias set)\n"
-			echo $name=(echo $path | cut -d \$'\n' -f $answer) > $configdir/alias
-			set -g path (echo $path | cut -d \$'\n' -f $answer)
-		else
-			echo "$answer is not a valid answer."
-			exit 1
-		end
-	# Throw an error if there are no directory matches
-	else 
-		echo "No "(set_color $c1)"directory"(set_color $fg)" match found."
-		exit 1
-	end
-end
-
-# This function tries to get the right file name
-function episode
-	set IFS
-
-	# Lists all video files in the directory
-	set episodes (find $mediadir/$path -type f -regex ".*\.\(avi\|mkv\|mp4\)" | rev | cut -d / -f -1 | rev)
-
-	# Calculates the zeros in a file name (for example two in 002 and one in 089)
-	set zerocount (math (echo $total | wc -c) - (echo $current | wc -c))
-	if test $zerocount -gt 0
-		set zero (printf 0%.0s (seq $zerocount))
-	end
-	
-	# Greps the right file (hopefully)
-	# Currently supports "E01", "ep01" & " 01"
-	set -g file (echo $episodes | grep "E$zero$current"[^0-9])
+	maim --hidecursor -s -b 3 -c 250,250,250 $uploadme 2> /dev/null
 	if test $status -ge 1
-		set -g file (echo $episodes | grep "ep$zero$current"[^0-9])
-		if test $status -ge 1
-			set -g file (echo $episodes | grep "$zero$current"[^0-9])
-		end
-	end
-
-	# Throw error if nothing is found
-	if test -z $file
-		echo "No "(set_color $c1)"episode"(set_color $fg)" match found."
+		echo "Selection cancelled."
 		exit 1
 	end
+
+	set -g word selection
 end
 
-# This function pauses mpd, and starts mpv
-function play
-	echo "Playing episode $current/$total, "(set_color $c1)"$name"(set_color $fg)"."
+# This function sets $file to a url
+function url
+	set type (echo $argv | rev | cut -d . -f 1 | rev)
+	set -g uploadme /tmp/url.$type
 
-	# Pause mpd
-	if test $pausempd = true
-		mpc -q pause
+	wget --quiet $argv -O $uploadme
+
+	set -g word url
+end
+
+# This function sets $file to a file
+function file
+	if test -f $argv
+		set -g uploadme $argv
+	else
+		echo "File not found."
+		exit 1
 	end
 
-	# Start mpv
-	mpv $options $mediadir/$path/$file
+	set -g word file
 end
 
+# This function sets $file to a full screen scrot
+function desktop
+	set -g uploadme /tmp/scrot.png
+
+	maim --hidecursor $uploadme
+
+	set -g word desktop
+end
+
+# This function uploads the $file
+function upload
+	set -g url (curl --silent -F key=$key -F file="@$uploadme" https://sr.ht/api/upload | grep -o -i "https://sr.ht/[a-z0-9.]*")
+end
+
+# This function logs the url,  copies the url to the clipboard, and/or opens the url in your browser
+function feedback
+	# Copy url to clipboard
+	if begin test $clipboard = true; and test $quiet = false; end
+		echo $url | xclip -selection primary
+		echo $url | xclip -selection clipboard
+	end
+
+	# Log url
+	if begin test $log = true; and test $quiet = false; end
+		echo $url >> $logfile
+	end
+
+	# Open url in browser
+	if begin test $browser = true; and test $quiet = false; end
+		$BROWSER $url
+	end
+
+	# Send notification
+	if begin test $notify = true; and test $quiet = false; end
+		notify "Punfed $word: $url" &
+	end
+	
+	# Send link
+	if test $quiet = true
+		echo $url
+	else
+		echo "Punfed $word: $url"
+	end
+end
 
 ## EXECUTE
 
-set realias false
+set quiet false
 
-if test (count $argv) -eq 1
+if test (count $argv) -ge 1
 	switch $argv[1]
 		case -h --help
-			echo -e "Usage: neet [options] [+/-]\n"
+			echo -e "Usage: punf [options] [file/url]\n"
 			echo "options:"
-			echo "  -e,   --edit            edit list"
-			echo "  -n,   --no-resume       disable resume playback"
-			echo "  -r,   --realias         forgets current alias"
+			echo "  -c,   --clipboard       upload your clipboard as text"
+			echo "  -s,   --selection       upload selection scrot"
+			echo "  -q,   --quiet           disable all feedback (for scripts using punf)"
+			echo "  -v,   --version         print version and exit"
 			echo "  -h,   --help            print help and exit"
 			exit 0
-		case -e --edit
-			eval $EDITOR $configdir/list
+		case -v --version
+			echo "punf 0.9.2"
 			exit 0
-		case -n --no-resume
-			info
-
-			set options $options --no-resume-playback
-		case -r --realias
-			info
-
-			set realias true
-		case "+*"
-			# Fail if there is a non + character in argv
-			if test (echo $argv[1] | sed s/+//g)
-				echo "Invalid option, use -h for help."
-				exit 1
-			end
-
-			info
-
-			# Get current episode and increment it by one
-			set amount (echo $argv[1] | wc -m)
-			set increment (math $current - 1 + $amount)
-
-			if test $increment -le $total
-				sed -i "s/+ $current\/$total/+ $increment\/$total/" "$configdir/list"
-				set current $increment
-			else
-				echo "Episode $total is the last episode."
-				exit 1
-			end
-		case "-*"
-			# Fail if there is a non - character in argv
-			if test (echo $argv[1] | sed s/-//g)
-				echo "Invalid option, use -h for help."
-				exit 1
-			end
-
-			info
-
-			# Get current episode and decrement it by one
-			set amount (echo $argv[1] | wc -m)
-			set decrement (math $current + 1 - $amount)
-
-			if test $decrement -ge 1
-				sed -i "s/+ $current\/$total/+ $decrement\/$total/" $configdir/list
-				set current $decrement
-			else
-				echo "There isn't an episode 0."
-				exit 1
-			end
+		case -c --clipboard
+			clipboard
+		case -s --selection
+			selection
+		case -q --quiet
+			set quiet true
+			file $argv[2]
+		case "http*"
+			url $argv[1]
 		case "*"
-			echo "Invalid option, use -h for help."
-			exit 1
+			file $argv[1]
 	end
 else
-	info
+	desktop
 end
 
-directory
-episode
-play
+upload
+feedback
