Add spurdo and misc updates

diff --git a/punf b/punf
--- a/punf
+++ b/punf
@@ -35,11 +35,41 @@ function clipboard
 	set -g word clipboard
 end
 
+# This function sets $file to a full screen scrot
+function desktop
+	set -g uploadme /tmp/scrot.png
+
+	maim --hidecursor $uploadme
+
+	set -g word desktop
+end
+
+# This function sets $file to a file
+function file
+	if test -f $argv
+		set -g uploadme $argv
+	else
+		echo "File not found."
+		exit 1
+	end
+
+	set -g word file
+end
+
+# This function sets $file to a selection stdin
+function stdin
+	set -g uploadme /tmp/stdin.txt
+
+	cat /dev/stdin > $uploadme
+
+	set -g word stdin
+end
+
 # This function sets $file to a selection scrot
 function selection
 	set -g uploadme /tmp/scrot.png
 
-	maim --hidecursor -s -b 3 -c 250,250,250 $uploadme 2> /dev/null
+	maim --hidecursor -s -b 3 -c 250,250,250 $uploadme ^ /dev/null
 	if test $status -ge 1
 		echo "Selection cancelled."
 		exit 1
@@ -58,52 +88,31 @@ function url
 	set -g word url
 end
 
-# This function sets $file to a file
-function file
-	if test -f $argv
-		set -g uploadme $argv
-	else
-		echo "File not found."
-		exit 1
-	end
-
-	set -g word file
-end
-
-# This function sets $file to a full screen scrot
-function desktop
-	set -g uploadme /tmp/scrot.png
-
-	maim --hidecursor $uploadme
-
-	set -g word desktop
-end
-
 # This function uploads the $file
 function upload
-	set -g url (curl --silent -F key=$key -F file="@$uploadme" https://sr.ht/api/upload | grep -o -i "https://sr.ht/[a-z0-9.]*")
+	set -g url (curl --silent -F key=$key -F file="@$uploadme" https://sr.ht/api/upload | grep -o -i "https://sr.ht/[a-z0-9._-]*")
 end
 
 # This function logs the url,  copies the url to the clipboard, and/or opens the url in your browser
 function feedback
 	# Copy url to clipboard
-	if begin test $clipboard = true; and test $quiet = false; end
+	if test $clipboard = true -a $quiet = false
 		echo $url | xclip -selection primary
 		echo $url | xclip -selection clipboard
 	end
 
 	# Log url
-	if begin test $log = true; and test $quiet = false; end
+	if test $log = true -a $quiet = false
 		echo $url >> $logfile
 	end
 
 	# Open url in browser
-	if begin test $browser = true; and test $quiet = false; end
+	if test $browser = true -a $quiet = false
 		$BROWSER $url
 	end
 
 	# Send notification
-	if begin test $notify = true; and test $quiet = false; end
+	if test $notify = true -a $quiet = false
 		notify "Punfed $word: $url" &
 	end
 	
@@ -127,13 +136,9 @@ if test (count $argv) -ge 1
 			echo "  -c,   --clipboard       upload your clipboard as text"
 			echo "  -s,   --selection       upload selection scrot"
 			echo "  -q,   --quiet           disable all feedback (for scripts using punf)"
-			echo "  -v,   --version         print version and exit"
 			echo "  -h,   --help            print help and exit"
 			exit 0
-		case -v --version
-			echo "punf 0.9.2"
-			exit 0
-		case -c --clipboard
+		case -p -c --clipboard
 			clipboard
 		case -s --selection
 			selection
@@ -146,7 +151,11 @@ if test (count $argv) -ge 1
 			file $argv[1]
 	end
 else
-	desktop
+	if test -t 0
+		desktop
+	else
+		stdin
+	end
 end
 
 upload
